name: PHP Lint on Develop

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour exécuter le job
    name: Lint PHP Files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: PHP Lint
        run: |

          find . -name "*.php" -print0 | xargs -0 -n1 php -l

