name: Develop Workflow

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: self-hosted
    name: PHP Lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PHP Lint
        run: |
          for file in $(find . -name "*.php"); do
            php -l "$file"
          done

  build:
    runs-on: self-hosted
    needs: lint
    name: Build Docker Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/your-docker-image:latest /var/www/html

  push:
    runs-on: self-hosted
    needs: build
    name: Push to DockerHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/your-docker-image:latest

  deploy:
    runs-on: self-hosted
    needs: push
    name: Deploy to Server
    steps:
      - name: SSH to Server and Deploy
        run: |
          ssh -i ~/.ssh/id_25519 naela@localhost << 'EOF'
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/your-docker-image:latest
          docker-compose up -d
          EOF














































































